//
//  Aeropush.h
//  react-native-aeropush
//
//  Objective-C++ header for the AeroPush Turbo Module.
//
//  This class conforms to <NativeAeropushSpec>, the protocol generated by
//  React Native Codegen from src/NativeAeropush.ts. The generated header
//  (AeropushSpec.h) is produced at build time by the host app's Codegen run,
//  so we import it conditionally and only when the New Architecture is on.
//
//  Native-to-native entry points (used by the AppDelegate bundle hook BEFORE
//  the JS runtime exists) are exposed as plain class methods that do not go
//  through the TurboModule machinery — see the "Launcher API" section.
//

#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

NS_ASSUME_NONNULL_BEGIN

@interface Aeropush : NSObject <RCTBridgeModule>

#pragma mark - Launcher API (native-to-native, no JS runtime required)

/**
 * The resolved bundle URL the app should boot from. Call this from your
 * AppDelegate's `bundleURL`/`sourceURLForBridge`. Returns the active OTA
 * bundle if one is set and valid, otherwise nil (caller should then fall
 * back to the binary's embedded bundle).
 *
 * This reads directly from NSUserDefaults and performs the Layer-1 launch
 * counter check + rollback synchronously, so it is safe to call at the very
 * top of app launch.
 */
+ (nullable NSURL *)bundleURL;

/**
 * Returns the raw active bundle file path (or nil). Lower level than
 * +bundleURL; does not run the launch-counter logic. Mainly for diagnostics.
 */
+ (nullable NSString *)activeBundlePath;

@end

NS_ASSUME_NONNULL_END
